// angular/angularforms/src/app/components/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import {FormControl,FormGroup,ReactiveFormsModule,Validators} from '@angular/forms';
import { NgFor,NgIf } from '@angular/common';
import {Router} from '@angular/router';

@Component({
  selector: 'app-register',
  imports: [NgIf,ReactiveFormsModule],
  templateUrl: './register.component.html',
  styleUrl: './register.component.css'
})
export class RegisterComponent implements OnInit {
  constructor(private router:Router){

  }
  ngOnInit(): void {
    this.registerForm.valueChanges.subscribe(val=>console.log(val));
  }

  submit(e:any){
    e.preventDefault();
    fetch("https://localhost:8000/api/user/regisztracio",{
      method:'POST',
      headers:{"Content-type":"application/json"},
      body:JSON.stringify(this.registerForm.value)

    })
    .then(res=>res.json())
    .then(valasz=>{
      if(!valasz.message){
        sessionStorage.setItem('usertoken',valasz);
        alert(valasz);
        this.router.navigate(['/']);
      } else {
        alert(valasz.message);
      }
    })
    .catch(err=>alert("Fetch hiba:"+err));
  }

  getError(path:string,errorName:string){
    const formControl=this.registerForm.get(path) as FormControl;
    if(formControl.untouched && formControl.pristine){
      return;
    }
    return formControl.errors?.[errorName];

  }

  registerForm=new FormGroup({
    username:new FormControl('',[Validators.required,Validators.minLength(3)]),
    email:new FormControl('',[Validators.required,Validators.email]),
    age:new FormControl('',[Validators.required,Validators.min(10),Validators.max(99)]),
    password:new FormControl('',[Validators.required,Validators.minLength(8)]),
    passwordagain:new FormControl('',[Validators.required,Validators.minLength(8)]),


  });

}

<div class="min-h-screen bg-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-md">
        <img class="mx-auto h-10 w-auto" src="https://www.svgrepo.com/show/301692/login.svg" alt="Workflow">
        <h2 class="mt-6 text-center text-3xl leading-9 font-extrabold text-gray-900">
            Regisztráció
        </h2>
        <p class="mt-2 text-center text-sm leading-5 text-gray-500 max-w">
            vagy
            <a href="#"
                class="font-medium text-blue-600 hover:text-blue-500 focus:outline-none focus:underline transition ease-in-out duration-150">
                belépés
            </a>
        </p>
    </div>

    <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
        <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
            <form (submit)="submit($event)" [formGroup]="registerForm">
                <div>
                    <label for="name" class="block text-sm font-medium leading-5  text-gray-700">Felhasználói név</label>
                    <div class="mt-1 relative rounded-md shadow-sm">
                        <input formControlName="username" id="username" name="username" placeholder="user" type="text" required=""
                            class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md placeholder-gray-400 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:text-sm sm:leading-5">
                            <div *ngIf="getError('username','required')">
                                A felhasználói név kötelező!
                            </div>
                            <div *ngIf="getError('username','minlength') as err">
                                A felhasználói név minimális hossza: {{err.requiredLength}}
                            </div>
                        <div class="hidden absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                            <svg class="h-5 w-5 text-red-500" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd"
                                    d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z"
                                    clip-rule="evenodd">
                                </path>
                            </svg>
                        </div>
                    </div>
                </div>

                

                <div class="mt-6">
                    <label for="email" class="block text-sm font-medium leading-5 text-gray-700">
                        Email cím
                    </label>
                    <div class="mt-1 relative rounded-md shadow-sm">
                        <input formControlName="email" id="email" name="email" placeholder="user@example.com" type="email"
                            required=""
                            class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md placeholder-gray-400 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:text-sm sm:leading-5">
                            <div *ngIf="getError('email','required')">
                                Kötelező megadni az e-mail címet!
                            </div>
                            <div *ngIf="getError('email','email')">
                                Email címet kell megadni!
                            </div>
                        <div class="hidden absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                            <svg class="h-5 w-5 text-red-500" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd"
                                    d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z"
                                    clip-rule="evenodd"></path>
                            </svg>
                        </div>
                    </div>
                </div>

                <div class="mt-6">
                    <label for="age" class="block text-sm font-medium leading-5 text-gray-700">
                        Életkor
                    </label>
                    <div class="mt-1 relative rounded-md shadow-sm">
                        <input formControlName="age" id="age" name="age" placeholder="életkor" type="email"
                            required=""
                            class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md placeholder-gray-400 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:text-sm sm:leading-5">
                            <div *ngIf="getError('age','required')">
                                Kötelező megadni az életkort!
                            </div>
                            <div *ngIf="getError('age','min') as err">
                                Az életkor nem lehet kisebb mint {{err.min}}
                            </div>
                            <div *ngIf="getError('age','max') as err">
                                Az életkor nem lehet nagyobb mint {{err.max}}
                            </div>
                        <div class="hidden absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                            <svg class="h-5 w-5 text-red-500" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd"
                                    d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z"
                                    clip-rule="evenodd"></path>
                            </svg>
                        </div>
                    </div>
                </div>

                <div class="mt-6">
                    <label for="password" class="block text-sm font-medium leading-5 text-gray-700">
                        Jelszó
                    </label>
                    <div class="mt-1 rounded-md shadow-sm">
                        <input formControlName="password" id="password" name="password" type="password" required=""
                            class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md placeholder-gray-400 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:text-sm sm:leading-5">
                            <div *ngIf="getError('password','required')">Adja meg a jelszót!</div>
                            <div *ngIf="getError('password','minlength') as err">A jelszó minimális hossza:{{err.requiredLength}} karakter</div>
                    </div>
                </div>

                <div class="mt-6">
                    <label  for="passwordagain" class="block text-sm font-medium leading-5 text-gray-700">
                        Jelszó megint
                    </label>
                    <div class="mt-1 rounded-md shadow-sm">
                        <input formControlName="passwordagain" id="passwordagain" name="passwordagain" type="password" required=""
                            class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md placeholder-gray-400 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:text-sm sm:leading-5">
                            <div *ngIf="getError('passwordagain','required')">Adja meg a jelszót!</div>
                            <div *ngIf="getError('passwordagain','minlength') as err">A jelszó minimális hossza:{{err.requiredLength}} karakter</div>

                    </div>
                </div>

                <div class="mt-6">
                    <span class="block w-full rounded-md shadow-sm">
                        <button type="submit"
                            class="w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition duration-150 ease-in-out">
                            Regisztráció
                        </button>
                    </span>
                </div>
            </form>

        </div>
    </div>
</div>

// user_login/frontend/src/components/Register.jsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";

function Register() {
  const navigate=useNavigate();

  const kuldes=(formData,method)=>{
    fetch(`${import.meta.env.VITE_BASE_URL}/api/user/regisztracio`,{
      method:method,
      headers:{"Content-type":"application/json"},
      body:JSON.stringify(formData)
    })
    .then(res=>res.json())
    .then(token=>{
      if(!token.message){
        sessionStorage.setItem('usertoken',token);
        alert("Sikeres regisztráció!");
        navigate('/');
      } else {
        alert(token.message);
      }
    })
    .catch(err=>alert(err));

  }
  const onSubmit=(e)=>{
    e.preventDefault();
    kuldes(formData,'POST');
  }

  let formObj={
    username:"",
    email:"",
    age:"",
    password:"",
    passwordAgain:""
  }

  const[formData,setFormData]=useState(formObj);

  const writeData=(e)=>{
    setFormData((prevState)=>({...prevState,[e.target.id]:e.target.value}));
  }

  return (
    <div>
      <h1 className="text-3xl font-bold text-center my-10">Regisztráció</h1>
      <form onSubmit={onSubmit} className="flex flex-col items-center justify-center">
      <input type="text" required id="username" value={formData.username} onChange={writeData} placeholder="felhasználói név" className="my-5 input input-bordered w-full max-w-xs" />
      <input type="text" required id="email" value={formData.email} onChange={writeData} placeholder="e-mail cím" className="my-5 input input-bordered w-full max-w-xs" />
      <input type="text" required id="age" value={formData.age} onChange={writeData} placeholder="életkor" className="my-5 input input-bordered w-full max-w-xs" />
      <input type="password" required id="password" value={formData.password} onChange={writeData} placeholder="jelszó" className="my-5 input input-bordered w-full max-w-xs" />
      <input type="password" required id="passwordAgain" value={formData.passwordAgain} onChange={writeData} placeholder="jelszó ismét" className="my-5 input input-bordered w-full max-w-xs" />
      <button type="submit" className="btn btn-primary">Küldés</button>

      </form>
    </div>
  )
}

export default Register
