// vue_proba/src/components/Menu.vue
<script setup>
import {RouterLink} from 'vue-router';
</script>

<template>
    <div class="navbar bg-slate-200 shadow-sm">
  <div class="flex-1">
    <RouterLink to="/" class="btn btn-ghost text-xl">Main</RouterLink>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal px-1">
      <li><RouterLink to="/typicode">Typicode</RouterLink></li>
      <li><RouterLink to="/randomusers">RandomUsers</RouterLink></li>
      <li>
        <details>
          <summary>Parent</summary>
          <ul class="bg-base-100 rounded-t-none p-2">
            <li><a>Link 1</a></li>
            <li><a>Link 2</a></li>
          </ul>
        </details>
      </li>
    </ul>
  </div>
</div>
</template>

// autok/frontend/src/components/Menu.jsx
import {Link} from 'react-router-dom';

function Menu() {
  return (
    <div className="navbar bg-teal-500">
      <div className="flex-1">
        <Link to="/" className="btn btn-ghost text-teal-100 text-xl">Főoldal</Link>
      </div>
      <div className="flex-none">
        <ul className="text-teal-100 menu menu-horizontal px-1">
          <li>
            <Link to="/autolista" >Autók listája</Link>
          </li>          
          <li>
            <Link to="/ujauto">Új autó felvitele</Link>
          </li>          
        </ul>
      </div>
    </div>
  );
}

export default Menu;
