// vue_proba/src/components/Typicode.vue
<script setup>
import {ref, onMounted} from "vue";
import Post from "./Post.vue";

const posts=ref([]);

const fetchPosts=()=>{
    fetch('https://jsonplaceholder.typicode.com/posts')
    .then(res=>res.json())
    .then(adat=>posts.value=adat)
    .catch(err=>alert(err));
}
onMounted(fetchPosts);
</script>

<template>
    <h2 class="text-center">Posztok száma:{{ posts.length }}</h2>
    
    <div class="flex flex-row flex-wrap items-center justify-center">
        <div  v-for="post in posts">
            <Post :post="post" />
        </div>
    </div>
</template>

// react_typescript/src/components/Typicode.tsx
import {useState,useEffect} from 'react';

type Post={
    userId:number,
    id:number,
    title:string,
    body:string
}

function Typicode() {
    const[posts,setPosts]=useState(Array<Post>);

    useEffect(()=>{
        fetch("https://jsonplaceholder.typicode.com/posts")
        .then(res=>res.json())
        .then(adat=>setPosts(adat))
        .catch(err=>alert(err));
    },[])

  return (
    <div>
        {
            posts.map((post)=>(<p key={post.id}>{post.id},{post.title}</p>))
        }
    </div>
  )
}

export default Typicode
