// angular/angularmorty/src/app/components/character/character.component.ts
import { Component, Input } from '@angular/core';
import { Character } from '../../model/character';


@Component({
  selector: 'app-character',
  imports: [],
  templateUrl: './character.component.html',
  styleUrl: './character.component.css'
})
export class CharacterComponent {

  @Input()
  result:Character={} as Character;

}

<div class="card lg:card-side w-96 bg-sky-200 shadow-sm m-2">
    <figure>
      <img
        src={{result.image}}
        alt="Album" />
    </figure>
    <div class="card-body">
      <h2 class="card-title">{{result.name}}</h2>
      <p>Status:{{result.status}}</p>
      <p>Species:{{result.species}}</p>
      <p>Gender:{{result.gender}}</p>

      
      <div class="card-actions justify-end">
        
      </div>
    </div>
  </div>

// rick_and_morty/src/components/Character.jsx


function Character({karakter}) {
  return (
    <div className="m-10 card lg:card-side bg-sky-300 shadow-xl">
    <figure>
      <img
        src={karakter.image}
        alt="Album" />
    </figure>
    <div className="card-body">
      <h2 className="card-title">{karakter.name}</h2>
      <p>Status:{karakter.status}</p>
      <p>Species:{karakter.species}</p>
      <p>Gender:{karakter.gender}</p>
      <div className="card-actions justify-end">
        
      </div>
    </div>
  </div>
  )
}

export default Character
