// rick_and_morty/src/components/Characters.jsx
import { useState,useEffect } from "react";
import Character from "./Character";


function Characters() {
    const [characters,setCharacters]=useState([]);
    const [info,setInfo]=useState({});
    const [page,setPage]=useState(1);
    
    useEffect(()=>{
        fetch(`https://rickandmortyapi.com/api/character?page=${page}`)
        .then(res=>res.json())
        .then(adat=>{
            setCharacters(adat.results);
            setInfo(adat.info);
        })
        .catch(err=>console.log(err));
    },[page]);

    const tovabb=()=>{
        if(page<info.pages){
            setPage(prev=>prev+1);
        }
    }

    const vissza=()=>{
        if(page>1){
            setPage(prev=>prev-1);
        }
    }

  return (
    <div>
        <div className="m-5 mx-auto w-40 join grid grid-cols-2">
            <button onClick={vissza} className="join-item btn btn-outline">Vissza</button>
            <button onClick={tovabb} className="join-item btn btn-outline">Tovább</button>
        </div>
        <div className="grid lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1 justify-items-center">
        {
            characters.map((karakter)=>(<Character key={karakter.id} karakter={karakter} />))
        }
        </div>
        
        <div className="m-5 mx-auto w-40 join grid grid-cols-2">
            <button onClick={vissza} className="join-item btn btn-outline">Vissza</button>
            <button onClick={tovabb} className="join-item btn btn-outline">Tovább</button>
        </div>
    </div>
  )
}

export default Characters

// angular/angularmorty/src/app/components/characters/characters.component.ts
import { Component, OnInit } from '@angular/core';
import { NgIf,NgFor } from '@angular/common';
import { CharacterComponent } from '../character/character.component';
import { Info } from '../../model/info';
import { Character } from '../../model/character';


@Component({
  selector: 'app-characters',
  imports: [NgIf,NgFor,CharacterComponent],
  templateUrl: './characters.component.html',
  styleUrl: './characters.component.css'
})
export class CharactersComponent implements OnInit {


  ngOnInit(): void {
    this.getCharacters();
  }

  

  //1.Inicializáljuk az objektumot
  // info:Info={
  //   count:0,
  //   pages:1,
  //   prev:"",
  //   next:""
  // };

  //2. A típusban opcionálissá tesszük a propertyket
  //info:Info={};

  //3. "as" használata, ha biztosak vagyunk abban, hogy mindig minden property kap értéket
  info:Info={} as Info;


  results:Character[]=[];

  page=1;
  isLoading=false;

  getCharacters(){
    this.isLoading=true;
    fetch(`https://rickandmortyapi.com/api/character?page=${this.page}`)
    .then(res=>res.json())
    .then(adat=>{
      this.info=adat.info;
      this.results=adat.results;
    })
    .catch(err=>alert(err))
    .finally(()=>this.isLoading=false);

  }

  tovabb(){
    if(this.page<this.info.pages){
      this.page+=1;
      this.getCharacters();
    }

  }

  vissza(){
    if(this.page>1){
      this.page-=1;
      this.getCharacters();
    }

  }

}

<h1 class="text-3xl text-sky-800 font-bold text-center m-5">Szereplők</h1>

<ng-container *ngIf="isLoading;else characterlist">
    <h1 class="text-2xl text-sky-500 text-center font-bold">Betöltés</h1>
</ng-container>

<ng-template #characterlist>
    <ng-container *ngIf="results.length>0;else ureslista">
        <div class="join flex flex-row justify-center">
            <button (click)="vissza()" class="join-item btn">«</button>
            <button class="join-item btn">{{page}}</button>
            <button (click)="tovabb()" class="join-item btn">»</button>
          </div>
        <div class="flex flex-row flex-wrap items-center justify-center">
        <ng-container *ngFor="let result of results">
            <!--<p class="text-center">{{result.name}}</p>-->
            <app-character [result]="result" />
        </ng-container>
        </div>
        <div class="join flex flex-row justify-center">
            <button (click)="vissza()" class="join-item btn">«</button>
            <button class="join-item btn">{{page}}</button>
            <button (click)="tovabb()" class="join-item btn">»</button>
          </div>
    </ng-container>

</ng-template>

<ng-template #ureslista>
    <h1 class="text-2xl text-sky-500 text-center font-bold">A lista üres!</h1>
</ng-template>
